export const InstructorsData = [
  {
    id: 0,
    name: "Никита",
    lastName: "Жуков",
    patronymic: "Эдуардович",
    photoMin: "/instructors/ZhukovMin.jpg",
    photoMax: "/instructors/ZhukovMax.jpg",
    is_on_main: true,
    info: [
      "Практикующий врач-невролог",
      "Врач доказательной медицины",
      "Медицинский директор сети клиник “Лахта”",
      "Автор расстрельного списка препаратов",
      "Автор серии книг “Модицина”",
      "Один из отцов основателей доказательной медицины в России",
      "Популяризатор медицинской науки",
    ],
    courses: [
      {
        name: "Неврология мечты",
        href: "c4",
        live: false,
      },
    ],
  },
  {
    id: 1,
    name: "Евгения",
    lastName: "Харченко",
    patronymic: "Владимировна",
    photoMin: "/instructors/KharchenkoMin.jpg",
    photoMax: "/instructors/KharchenkoMax.jpg",
    is_on_main: true,
    info: [
      "Врач-онколог, к.м.н.",
      "Основатель платформы MD.school",
      "Спикер TEDx",
      "30+ международных грантов",
      "Спикер более 50 российских и международных конференций",
      "Проходила повышение квалификации в медицинской школе Гарварда и в Оксфорде",
      "Лауреат премии Американского общества клинической онкологии за развитие и образование",
      "Работала в ведущей онкологической клинике мира и институте онкологии Южной Швейцарии",
    ],
    courses: [
      {
        name: "Школа по Медицинской Статистике",
        href: "c0",
        live: false,
      },
      {
        name: "MDclub",
        href: "mdclubCourse",
        live: false,
      },
    ],
  },
  {
    id: 2,
    name: "Галина",
    lastName: "Киреева",
    patronymic: "Сергеевна",
    photoMin: "/instructors/KireevaMin.jpg",
    photoMax: "/instructors/KireevaMax.jpg",
    is_on_main: true,
    info: [
      "Образование: высшее фармацевтическое – СПХФА (СПб)",
      "Кандидат биологических наук (специальность «онкология»)",
      "Последипломное образование – Harvard Medical School",
      "Грантополучатель российских (РНФ, РФФИ) и международных научных фондов",
      "Более 100 научных публикаций, из которых 50 – в журналах, индексируемых в базах Scopus, WoS",
      "Индекс Хирша по РИНЦ – 8, Scopus – 4, WoS – 3",
      "Консультирование и корректировки по процессу написания диссертации – более 30 коллег (кандидатских и докторских)",
      "Опыт работы: научный сотрудник, ученый секретарь, проректор",
    ],
    courses: [
      {
        name: "Школа по Медицинской Статистике",
        href: "c0",
        live: false,
      },
      {
        name: "MDclub",
        href: "mdclubCourse",
        live: false,
      },
    ],
  },
  {
    id: 3,
    name: "Владислав",
    lastName: "Осетник",
    patronymic: "Константинович",
    photoMin: "/instructors/OsetnikMin.jpg",
    photoMax: "/instructors/OsetnikMax.jpg",
    is_on_main: false,
    info: [
      "Врач-онколог",
      "Создатель платформы MD.school",
      "Окончил программу Harvard Medical School по образованию в медицине",
      "Прошел программы по биостатистике и клиническим исследованиям от Йельского университета и университета Джонса Хопкинса",
      "Обладатель 14 грантов на международные стажировки",
      "Автор 12 статей, индексируемых в базах Scopus и Web of Science",
    ],
    courses: [
      {
        name: "Школа по Медицинской Статистике",
        href: "c0",
        live: false,
      },
      {
        name: "Сам себе статистик",
        href: "c1",
        live: false,
      },
      {
        name: "MDclub",
        href: "mdclubCourse",
        live: false,
      },
    ],
  },
  {
    id: 4,
    name: "Яна",
    lastName: "Катасонова",
    patronymic: "Вячеславовна",
    photoMin: "/instructors/KatasonovaMin.jpg",
    photoMax: "/instructors/KatasonovaMax.jpg",
    is_on_main: false,
    info: [
      "Доказательный врач-офтальмолог",
      "Автор пособия по миопии и очковым линзам",
      "Член European Society of Ophthalmology",
      "Автор научно-популярного блога @smolyar.ya",
      "Пишет  книгу в издательстве ЭКСМО для тревожных родителей и их детей с заболеваниями глаз",
    ],
    courses: [
      {
        name: "Базовая офтальмология",
        href: "c3",
        live: false,
      },
    ],
  },
  {
    id: 5,
    name: "Иван",
    lastName: "Лабетов",
    patronymic: "Антонович",
    photoMin: "/instructors/LabetovMin.jpg",
    photoMax: "/instructors/LabetovMax.jpg",
    is_on_main: false,
    info: [
      "Врач-уролог",
      "Соавтор 2х патентов на изобретения, а также статей в Российских и международных журналах",
      "Принимает участие в проведении и обработке результатов исследований лаборатории нейропротезов Института трансляционной медицины СПбГУ",
      "Владеет R - языком программирования для статистической обработки",
      "Успешно окончил курсы по статистике и науке о данных от 2GIS, Института биоинформатики и университета Джона Хопкинса",
    ],
    courses: [
      {
        name: "Сам себе статистик",
        href: "c1",
        live: false,
      },
      {
        name: "Школа по Медицинской Статистике",
        href: "c0",
        live: false,
      },
      {
        name: "MDclub",
        href: "mdclubCourse",
        live: false,
      },
    ],
  },
  {
    id: 6,
    name: "Мария",
    lastName: "Садовничая",
    patronymic: "Игоревна",
    photoMin: "/instructors/SadovnichayaMin.jpg",
    photoMax: "/instructors/SadovnichayaMax.jpg",
    is_on_main: false,
    info: [
      "Врач-педиатр",
      "Врач доказательной медицины",
      "Член Американской Академии педиатров, Союза педиатров России",
      "Победитель научных конференций",
      "Участник европейского парламента в Копенгагене",
      "Многократный спикер конференций для врачей и родителей",
      "Подтверждает диплом в США",
    ],
    courses: [
      {
        name: "Базовая педиатрия",
        href: "c5",
        live: false,
      },
    ],
  },
  {
    id: 7,
    name: "Владимир",
    lastName: "Кушнарёв",
    patronymic: "Андреевич",
    photoMin: "/instructors/KushnarevMin.jpg",
    photoMax: "/instructors/KushnarevMax.jpg",
    is_on_main: false,
    info: [
      "Врач-патологоанатом, к.м.н",
      "Associate alumni Harvard Medical School",
      "Со-основатель образовательного проекта для онкологов и патологоанатомов Cancer Chameleon",
    ],
    courses: [
      {
        name: "Введение в фундаментальную онкологию",
        href: "c2",
        live: false,
      },
    ],
  },
  {
    id: 8,
    name: "Варвара",
    lastName: "Веретюк",
    patronymic: "Васильевна",
    photoMin: "/instructors/VeretukMin.jpg",
    photoMax: "/instructors/VeretukMax.jpg",
    is_on_main: false,
    info: [
      "Врач-терапевт",
      "Ассистент кафедры неотложной терапии с эндокринологией и профпатологией Новосибирского государственного медицинского университета",
      "Ведущий терапевт сети клиник “Здравица” г.Новосибирск",
      "Гастроэнтеролог, специалист по питанию",
      "Автор блога @varvara_veretyuk",
    ],
    courses: [],
  },
];
